<?php
/**
 * Language switcher template, Porto Theme, with Flags
 */
?>
<?php
// @codingStandardsIgnoreFile

/** @var \IMI\StoreSwitch\ViewModel\StoreSwitchModel $viewModel */
/** @var Magento\Store\Block\Switcher $block */
$viewModel = $block->getData('view_model');
$context = $block->getData('context');

?>
<?php
    $_helper = $this->helper('Smartwave\Porto\Helper\Data');
    $is_demo = 0;
?>

<?php if ($viewModel->isEnabled() && $viewModel->isEnabledOnOtherStores()): ?>
    <?php $websites = $viewModel->getWebsites(); ?>
    <?php $id = $context . ($block->getIdModifier() ? '-' . $block->getIdModifier() : '') ?>
    <div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?php /* @escapeNotVerified */ echo $id?>">
        <strong class="label switcher-label"><span><?php /* @escapeNotVerified */ echo __('Language') ?></span></strong>
        <div class="actions dropdown options switcher-options">
            <?php $currentStore = $viewModel->getCurrentStore(); ?>
            <div class="action toggle switcher-trigger" id="switcher-language-trigger<?php /* @escapeNotVerified */ echo $id?>">
                <strong class="view-<?php echo $block->escapeHtml($block->getCurrentStoreCode()) ?>">
                    <?php if($_helper->getConfig('porto_settings/header/language_flag')): ?>
                        <img src="<?php echo $_helper->getBaseUrl().'wysiwyg/smartwave/porto/flags/'.$block->escapeHtml($block->escapeHtml($block->getCurrentStoreCode())).'.png'; ?>" alt="" />
                    <?php endif; ?>
                    <span><?= $block->escapeHtml($viewModel->getStoreSwitchLabel($currentStore)) ?></span>
                </strong>
            </div>
            <ul class="dropdown switcher-dropdown"
                data-mage-init='{"dropdownDialog":{
                    "appendTo":"#switcher-language<?php /* @escapeNotVerified */ echo $id ?> > .options",
                    "triggerTarget":"#switcher-language-trigger<?php /* @escapeNotVerified */ echo $id ?>",
                    "closeOnMouseLeave": false,
                    "triggerClass":"active",
                    "parentClass":"active",
                    "buttons":null}}'>
                <?php foreach ($websites as $website): ?>
                    <?php /** @var \Magento\Store\Model\Store $_store */?>
                    <?php foreach ($website->getStoreCollection() as $_lang): ?>
                        <?php if ($_lang->getId() != $block->getCurrentStoreId()): ?>
                            <li class="view-<?php echo $block->escapeHtml($_lang->getCode()); ?> switcher-option">
                                <a href="#" data-post='<?php echo $this->getTargetStorePostData($_lang); ?>'>
                                    <?php if($_helper->getConfig('porto_settings/header/language_flag')): ?>
                                        <img src="<?php echo $_helper->getBaseUrl().'wysiwyg/smartwave/porto/flags/'.$block->escapeHtml($_lang->getCode()).'.png'; ?>" alt="" />
                                    <?php endif; ?>
                                    <?php echo $block->escapeHtml($viewModel->getStoreSwitchLabel($_lang)) ?></a>
                            </li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>

